run:
  tests: true

linters-settings:
  depguard:
    rules:
      main:
        allow: [
          "testing",
          "fmt",
          "slices",
          "github.com/stretchr/testify/require",
        ]