[loggers]
level = "ingo" # possible values: info, warn, error, debug

[storage]
type = "inmemory" # possible values: inmemory, postgres

[storage.postgres]
dataSourceName = "postgres://postgres:postgres@localhost:5432/eventsdb"

[httpserver]
host = "localhost"
port = "12345"

[grpcserver]
host = "localhost"
port = "23456"